### ISSUE TITLE
在转发 下面 没有自动变成表情包

### ISSUE THREAD

**Issue by Huxzhi** [AS042971/bilibili-bobo#1]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/49866441/176814198-56fb12e1-01d2-4954-98c2-44ffb6e8f201.png">

还有就是 表情包有点小，能不能放大一点

<img width="609" alt="image" src="https://user-images.githubusercontent.com/49866441/176814436-faed17d8-b873-4317-9804-121dd49e8fde.png">

**Comment by AS042971** [comment]
动态中的表情包本来就是这个大小(你也可以试试别的)
转发列表暂不考虑适配
