### ISSUE TITLE
点赞动画

### ISSUE THREAD

**Issue by Gimyou** [AS042971/bilibili-bobo#11]
今天留意到点赞动画是塔菲的，无论是视频点赞还是动态点赞。不知道是bug还是什么原因。
![批注 2022-07-14 125203](https://user-images.githubusercontent.com/94677855/178901714-52294c3f-94e6-4a95-8422-4261f90f11e4.jpg)
![批注 2022-07-14 125346](https://user-images.githubusercontent.com/94677855/178901946-49a63a1d-df23-491e-bc05-7047e512f619.jpg)

**Comment by milkiq** [comment]
是 bug，后续版本已修复，没有及时看到 issue，抱歉
